version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DBNAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network

  server:
    build: .
    depends_on:
      - db
    entrypoint: ["./wait-for-it.sh", "db:5432", "--", "./server"]
    env_file: .env
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      PG_HOST: db

volumes:
  pgdata:

networks:
  app-network: